### ISSUE TITLE
Slow command running with isolated: true

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-gobstones-runner#17] opened 2018-01-02 19:11 UTC
With both servers started locally, the request time is about 2 seconds

```bash
127.0.0.1 - - [02/Jan/2018:16:08:10 -0300] "POST /test HTTP/1.1" 200 1273 2.0182
127.0.0.1 - - [02/Jan/2018:16:08:44 -0300] "POST /test HTTP/1.1" 200 1273 1.9583
127.0.0.1 - - [02/Jan/2018:16:10:36 -0300] "POST /test HTTP/1.1" 200 1273 2.6443
127.0.0.1 - - [02/Jan/2018:16:10:39 -0300] "POST /test HTTP/1.1" 200 1273 1.8920
127.0.0.1 - - [02/Jan/2018:16:10:42 -0300] "POST /test HTTP/1.1" 200 1273 1.9624
127.0.0.1 - - [02/Jan/2018:16:10:45 -0300] "POST /test HTTP/1.1" 200 1273 2.0506
```

**Comment by rodri042** [comment] 2018-01-04 04:13
Can't reproduce this :confused: 

```
➜  mumuki-gobstones-runner git:(fix-final-board-postcondition) RACK_ENV=development bundle exec rackup --port 4000 --host 0.0.0.0
Puma starting in single mode...
* Version 3.11.0 (ruby 2.3.1-p112), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:4000
Use Ctrl-C to stop
127.0.0.1 - - [04/Jan/2018:04:09:52 +0000] "POST /test HTTP/1.1" 200 1257 0.7230
127.0.0.1 - - [04/Jan/2018:04:10:10 +0000] "POST /test HTTP/1.1" 200 1257 0.7154
127.0.0.1 - - [04/Jan/2018:04:10:13 +0000] "POST /test HTTP/1.1" 200 1257 0.7192
127.0.0.1 - - [04/Jan/2018:04:10:16 +0000] "POST /test HTTP/1.1" 200 1257 0.7095
127.0.0.1 - - [04/Jan/2018:04:10:22 +0000] "POST /test HTTP/1.1" 200 918 0.6972
```

Could you test in a production machine?

**Comment by rodri042** [comment] 2018-01-16 23:50
After merging https://github.com/mumuki/mumuki-gobstones-runner/pull/28 the time improved, but I'm leaving the issue open to follow this:

> Still we have to do some work on improving the speed. Did you discover which gems are causing the problem?

Nope. I just did some debugging and the `run!` method of the precompile hook takes almost all the response time. **Only when Docker is used**.

With `isolated: true`:
![screenshot3](https://user-images.githubusercontent.com/1631752/35006323-08853a7c-faff-11e7-87f1-6b6e35518365.png)

With `isolated: false`:
![screenshot2](https://user-images.githubusercontent.com/1631752/35006337-120a71ac-faff-11e7-8414-4cc77411494b.png)

**Comment by flbulgarelli** [comment] 2018-04-01 22:41
Closing. This was fixed when gobstones runner architecture changed in https://github.com/mumuki/mumuki-gobstones-runner/pull/28

**Closed by flbulgarelli** 2018-04-01 22:41 UTC
Labels: pending-review
